<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ngày thi dự kiến - Lái Vui</title><link rel="stylesheet" href="${ctx}/assets/css/style.css"><link rel="stylesheet" href="${ctx}/assets/css/layout.css">
<style>
.tent-grid{display:grid;grid-template-columns:340px minmax(0,1fr);gap:1.2rem;align-items:start}.tent-card{background:#fff;border:1px solid #dbe3ef;border-radius:14px;padding:1.2rem}.tent-title{margin:0 0 .4rem;color:#0f172a}.tent-hint{color:#64748b;font-size:.9rem;line-height:1.5}.tent-form{display:grid;gap:.85rem}.tent-table{width:100%;border-collapse:collapse}.tent-table th,.tent-table td{padding:.75rem;border-bottom:1px solid #e2e8f0;text-align:left}.tent-table th{background:#f8fafc;color:#475569;font-size:.78rem}.slot{font-weight:700;color:#047857}.slot.full{color:#dc2626}.actions{display:flex;gap:.5rem;flex-wrap:wrap}.notice{padding:.8rem 1rem;border-radius:10px;margin-bottom:1rem}.ok{background:#ecfdf5;color:#047857}.err{background:#fef2f2;color:#b91c1c}@media(max-width:900px){.tent-grid{grid-template-columns:1fr}}
</style></head><body class="has-side-nav-bar"><jsp:include page="/views/layout/sidebar-managingstaff.jsp"><jsp:param name="activeSidebar" value="ngay-du-kien"/></jsp:include><div class="dashboard-shell">
<main class="main-content"><div class="page-header"><div><p class="breadcrumb">Dashboard / Ngày thi dự kiến</p><h1 class="page-title">Quản lý ngày thi dự kiến</h1><p class="page-subtitle">Tạo ngày để thí sinh đã duyệt lựa chọn. Mỗi ngày và hạng GPLX nhận tối đa 50 hồ sơ.</p></div></div>
<c:if test="${not empty sessionScope.tentativeSuccess}"><div class="notice ok">${sessionScope.tentativeSuccess}</div><c:remove var="tentativeSuccess" scope="session"/></c:if>
<c:if test="${not empty sessionScope.tentativeError}"><div class="notice err">${sessionScope.tentativeError}</div><c:remove var="tentativeError" scope="session"/></c:if>
<div class="tent-grid"><section class="tent-card"><h2 class="tent-title">Tạo ngày dự kiến</h2><p class="tent-hint">Ngày dự kiến không tạo phiên thi chính thức.</p>
<form class="tent-form" method="post" action="${ctx}/manager/tentative-exam-dates"><label>Ngày dự kiến<input class="input-field" type="date" name="examDate" min="${today}" required></label><label>Hạng GPLX<select class="input-field" name="licenceId" required><option value="">Chọn hạng</option><c:forEach var="l" items="${licences}"><option value="${l.licenceId}">${l.licenceClass}</option></c:forEach></select></label><button class="btn-filter" type="submit">Tạo ngày dự kiến</button></form></section>
<section class="tent-card"><h2 class="tent-title">Danh sách ngày dự kiến</h2><nav style="display:flex;gap:.5rem;margin:1rem 0"><a class="${activeTab eq 'active' ? 'btn-filter' : 'btn-export'}" href="${ctx}/manager/tentative-exam-dates?tab=active" style="text-decoration:none">Đang mở (${activeCount})</a><a class="${activeTab eq 'expired' ? 'btn-filter' : 'btn-export'}" href="${ctx}/manager/tentative-exam-dates?tab=expired" style="text-decoration:none">Đã hết hạn (${expiredCount})</a></nav><div style="overflow:auto"><table class="tent-table"><thead><tr><th>Ngày</th><th>Hạng</th><th>Đã chọn</th><th>Còn lại</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach var="d" items="${dates}"><tr><td><fmt:formatDate value="${d.examDate}" pattern="dd/MM/yyyy"/></td><td><strong>${d.licenceClass}</strong></td><td>${d.registeredCount}/50</td><td><span class="slot ${d.full ? 'full' : ''}">${d.remainingSlots}</span></td><td><div style="display:flex;gap:.4rem;white-space:nowrap"><a class="btn-export" href="${ctx}/manager/tentative-exam-dates?dateId=${d.id}&amp;page=${currentPage}&amp;tab=${activeTab}">Xem danh sách</a><c:if test="${d.registeredCount eq 0}"><form method="post" action="${ctx}/manager/tentative-exam-dates" onsubmit="return confirm('Xóa ngày thi dự kiến này?');"><input type="hidden" name="action" value="delete"><input type="hidden" name="dateId" value="${d.id}"><input type="hidden" name="returnTab" value="${activeTab}"><button class="btn-reset" type="submit">Xóa</button></form></c:if></div></td></tr></c:forEach>
<c:if test="${empty dates}"><tr><td colspan="5" style="text-align:center;color:#64748b;padding:2rem">Chưa có ngày thi dự kiến.</td></tr></c:if></tbody></table></div>
<c:if test="${totalPages gt 1}"><nav class="pagination-nav" style="margin-top:1rem"><c:forEach var="p" begin="1" end="${totalPages}"><a class="page-btn ${p eq currentPage ? 'active' : ''}" href="${ctx}/manager/tentative-exam-dates?tab=${activeTab}&amp;page=${p}">${p}</a></c:forEach></nav></c:if></section></div>
<c:if test="${not empty selectedDate}"><section class="tent-card" style="margin-top:1.2rem"><div style="display:flex;justify-content:space-between;gap:1rem;align-items:start;flex-wrap:wrap"><div><h2 class="tent-title">Hồ sơ chờ thi ngày <fmt:formatDate value="${selectedDate.examDate}" pattern="dd/MM/yyyy"/> · Hạng ${selectedDate.licenceClass}</h2><p class="tent-hint">${candidateTotal}/50 hồ sơ. PDF chính thức được tạo tại bước này.</p></div><div class="actions"><a class="btn-export" href="${ctx}/manager/tentative-exam-dates?dateId=${selectedDate.id}&export=excel">Xuất Excel</a><a class="btn-filter" href="${ctx}/manager/tentative-exam-dates?dateId=${selectedDate.id}&export=zip">Tải bộ hồ sơ PDF</a></div></div>
<div style="overflow:auto"><table class="tent-table"><thead><tr><th>Mã HS</th><th>CCCD</th><th>Họ tên</th><th>Email</th><th>Hạng</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach var="d" items="${candidates}"><tr><td>#${d.registrationId}</td><td>${d.profile.govIdNo}</td><td><strong><c:out value="${d.profile.fullName}"/></strong></td><td><c:out value="${d.user.email}"/></td><td>${d.licenceDisplayClass}</td><td>Chờ thi</td><td><a class="btn-export" href="${ctx}/manager/tentative-exam-dates?dateId=${selectedDate.id}&export=pdf&registrationId=${d.registrationId}">PDF</a></td></tr></c:forEach><c:if test="${empty candidates}"><tr><td colspan="7" style="text-align:center;padding:2rem;color:#64748b">Chưa có hồ sơ chọn ngày này.</td></tr></c:if></tbody></table></div>
<c:if test="${candidatePages gt 1}"><nav class="pagination-nav" style="margin-top:1rem"><c:forEach var="p" begin="1" end="${candidatePages}"><a class="page-btn ${p eq candidatePage ? 'active' : ''}" href="${ctx}/manager/tentative-exam-dates?dateId=${selectedDate.id}&amp;tab=${activeTab}&amp;page=${currentPage}&amp;candidatePage=${p}">${p}</a></c:forEach></nav></c:if></section></c:if>
</main><jsp:include page="/views/layout/footer.jsp"><jsp:param name="standalone" value="false"/></jsp:include></div></body></html>
