<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ngày thi dự kiến - Lái Vui</title><link rel="stylesheet" href="${ctx}/assets/css/style.css"><link rel="stylesheet" href="${ctx}/assets/css/layout.css">
<style>
.tent-grid{display:grid;grid-template-columns:340px minmax(0,1fr);gap:1.2rem;align-items:start}.tent-card{background:#fff;border:1px solid #dbe3ef;border-radius:14px;padding:1.2rem}.tent-title{margin:0 0 .4rem;color:#0f172a}.tent-hint{color:#64748b;font-size:.9rem;line-height:1.5}.tent-form{display:grid;gap:.85rem}.tent-table{width:100%;border-collapse:collapse}.tent-table th,.tent-table td{padding:.75rem;border-bottom:1px solid #e2e8f0;text-align:left}.tent-table th{background:#f8fafc;color:#475569;font-size:.78rem}.tent-table tbody tr{transition:background-color .18s ease}.tent-table tbody tr.tent-row-selected td{background:#eff6ff;border-bottom-color:#bfdbfe}.tent-table tbody tr.tent-row-selected td:first-child{box-shadow:inset 4px 0 #0b5ed7}.tent-table tbody tr.tent-row-selected strong{color:#0755b5}.slot{font-weight:700;color:#047857}.slot.full{color:#dc2626}.actions{display:flex;gap:.5rem;flex-wrap:wrap}.notice{padding:.8rem 1rem;border-radius:10px;margin-bottom:1rem}.ok{background:#ecfdf5;color:#047857}.err{background:#fef2f2;color:#b91c1c}.cancel-badge,.lock-badge{display:inline-flex;padding:.25rem .55rem;border-radius:999px;font-size:.78rem;font-weight:700}.cancel-badge{background:#fee2e2;color:#b91c1c}.lock-badge{background:#fef3c7;color:#92400e}.cancel-form{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.75rem;align-items:end;margin-top:1rem;padding:1rem;border:1px solid #fecaca;border-radius:12px;background:#fff7f7}.cancel-form label{display:grid;gap:.4rem;font-weight:700;color:#7f1d1d}.cancel-form textarea{min-height:72px;resize:vertical}.cancel-summary{margin-top:1rem;padding:1rem;border:1px solid #fecaca;border-radius:12px;background:#fff7f7;color:#7f1d1d}.cancel-summary p{margin:.35rem 0 0}.deadline-note{display:block;margin-top:.35rem;color:#64748b;font-size:.78rem}@media(max-width:900px){.tent-grid{grid-template-columns:1fr}.cancel-form{grid-template-columns:1fr}}
.police-badge{display:inline-flex;padding:.25rem .55rem;border-radius:999px;font-size:.78rem;font-weight:700}.police-badge.not-sent{background:#f1f5f9;color:#475569}.police-badge.pending{background:#fef3c7;color:#92400e}.police-badge.completed{background:#dcfce7;color:#166534}.tent-table td:last-child>div{flex-wrap:wrap!important;white-space:normal!important}
</style></head><body class="has-side-nav-bar"><jsp:include page="/views/layout/sidebar-managingstaff.jsp"><jsp:param name="activeSidebar" value="ngay-du-kien"/></jsp:include><div class="dashboard-shell">
<main class="main-content"><div class="page-header"><div><p class="breadcrumb">Dashboard / Ngày thi dự kiến</p><h1 class="page-title">Quản lý ngày thi dự kiến</h1><p class="page-subtitle">Tạo ngày để thí sinh đã duyệt lựa chọn. Mỗi ngày nhận tối đa 50 hồ sơ và tự động khóa trước 07 ngày làm việc.</p></div></div>
<c:if test="${policeReturnedCount gt 0}"><div class="notice ok"><strong>CSGT đã trả ${policeReturnedCount} danh sách thi chính thức.</strong> Trung tâm có thể tải danh sách và <a href="${ctx}/manager/exam-schedules">tạo phiên thi chính thức</a>.</div></c:if>
<c:if test="${not empty sessionScope.tentativeSuccess}"><div class="notice ok">${sessionScope.tentativeSuccess}</div><c:remove var="tentativeSuccess" scope="session"/></c:if>
<c:if test="${not empty sessionScope.tentativeError}"><div class="notice err">${sessionScope.tentativeError}</div><c:remove var="tentativeError" scope="session"/></c:if>
<div class="tent-grid"><section class="tent-card"><h2 class="tent-title">Tạo ngày dự kiến</h2><p class="tent-hint">Ngày dự kiến không tạo phiên thi chính thức.</p>
<form class="tent-form" method="post" action="${ctx}/manager/tentative-exam-dates"><label>Ngày dự kiến<input class="input-field" type="date" name="examDate" min="${minimumExamDate}" required></label><label>Hạng GPLX<select class="input-field" name="licenceId" required><option value="">Chọn hạng</option><c:forEach var="l" items="${licences}"><option value="${l.licenceId}">${l.licenceClass}</option></c:forEach></select></label><button class="btn-filter" type="submit">Tạo ngày dự kiến</button></form></section>
<section class="tent-card"><h2 class="tent-title">Danh sách ngày dự kiến</h2><nav style="display:flex;gap:.5rem;margin:1rem 0;flex-wrap:wrap"><a class="${activeTab eq 'active' ? 'btn-filter' : 'btn-export'}" href="${ctx}/manager/tentative-exam-dates?tab=active" style="text-decoration:none">Đang mở (${activeCount})</a><a class="${activeTab eq 'expired' ? 'btn-filter' : 'btn-export'}" href="${ctx}/manager/tentative-exam-dates?tab=expired" style="text-decoration:none">Đã hết hạn (${expiredCount})</a><a class="${activeTab eq 'cancelled' ? 'btn-filter' : 'btn-export'}" href="${ctx}/manager/tentative-exam-dates?tab=cancelled" style="text-decoration:none">Đã hủy (${cancelledCount})</a></nav><div style="overflow:auto"><table class="tent-table"><thead><tr><th>Ngày</th><th>Hạng</th><th>Đã chọn</th><th>Còn lại</th><th>CSGT</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach var="d" items="${dates}"><tr class="${not empty selectedDate and selectedDate.id eq d.id ? 'tent-row-selected' : ''}"><td><fmt:formatDate value="${d.examDate}" pattern="dd/MM/yyyy"/><c:if test="${not d.cancelled}"><span class="deadline-note">Tự khóa: <fmt:formatDate value="${d.cancellationDeadline}" pattern="dd/MM/yyyy"/></span></c:if></td><td><strong>${d.licenceClass}</strong></td><td>${d.registeredCount}/50</td><td><c:choose><c:when test="${d.cancelled}"><span class="cancel-badge">Đã hủy</span></c:when><c:when test="${d.locked}"><span class="lock-badge">Đã khóa</span></c:when><c:otherwise><span class="slot ${d.full ? 'full' : ''}">${d.remainingSlots}</span></c:otherwise></c:choose></td><td><c:choose><c:when test="${d.policeCompleted}"><span class="police-badge completed">Đã duyệt</span></c:when><c:when test="${d.pendingPolice}"><span class="police-badge pending">Đang xử lý</span></c:when><c:otherwise><span class="police-badge not-sent">Chưa gửi</span></c:otherwise></c:choose></td><td><div style="display:flex;gap:.4rem;white-space:nowrap"><a class="${not empty selectedDate and selectedDate.id eq d.id ? 'btn-filter' : 'btn-export'}" href="${ctx}/manager/tentative-exam-dates?dateId=${d.id}&amp;page=${currentPage}&amp;tab=${activeTab}" aria-current="${not empty selectedDate and selectedDate.id eq d.id ? 'true' : 'false'}">${not empty selectedDate and selectedDate.id eq d.id ? 'Đang xem' : (d.cancelled ? 'Xem lý do' : 'Xem danh sách')}</a><c:if test="${d.sendableToPolice}"><form method="post" action="${ctx}/manager/tentative-exam-dates" style="margin:0" onsubmit="return confirm('Gửi danh sách này tới CSGT và khóa ngay việc đăng ký?');"><input type="hidden" name="action" value="sendPolice"><input type="hidden" name="dateId" value="${d.id}"><button class="btn-filter" type="submit">Gửi CSGT</button></form></c:if><c:if test="${activeTab eq 'active' and d.cancellable}"><a class="btn-reset" href="${ctx}/manager/tentative-exam-dates?dateId=${d.id}&amp;page=${currentPage}&amp;tab=active#cancel-date-form" style="text-decoration:none">Hủy</a></c:if></div></td></tr></c:forEach>
<c:if test="${empty dates}"><tr><td colspan="6" style="text-align:center;color:#64748b;padding:2rem">Chưa có ngày thi dự kiến.</td></tr></c:if></tbody></table></div>
<c:if test="${totalPages gt 1}"><nav class="pagination-nav" style="margin-top:1rem"><c:forEach var="p" begin="1" end="${totalPages}"><a class="page-btn ${p eq currentPage ? 'active' : ''}" href="${ctx}/manager/tentative-exam-dates?tab=${activeTab}&amp;page=${p}">${p}</a></c:forEach></nav></c:if></section></div>
<c:if test="${not empty selectedDate}"><section class="tent-card" style="margin-top:1.2rem"><div style="display:flex;justify-content:space-between;gap:1rem;align-items:start;flex-wrap:wrap"><div><h2 class="tent-title">Ngày dự kiến <fmt:formatDate value="${selectedDate.examDate}" pattern="dd/MM/yyyy"/> · Hạng ${selectedDate.licenceClass}</h2><p class="tent-hint">${candidateTotal}/50 hồ sơ đã ghi nhận · CSGT: <strong>${selectedDate.policeCompleted ? 'Đã hoàn tất' : (selectedDate.pendingPolice ? 'Đang xử lý' : 'Chưa gửi')}</strong></p></div><c:if test="${not selectedDate.cancelled}"><div class="actions"><a class="btn-export" href="${ctx}/manager/tentative-exam-dates?dateId=${selectedDate.id}&export=excel">Xuất Excel</a><c:if test="${selectedDate.sendableToPolice}"><form method="post" action="${ctx}/manager/tentative-exam-dates" onsubmit="return confirm('Gửi toàn bộ hồ sơ của ngày này tới CSGT và khóa ngay việc đăng ký?');"><input type="hidden" name="action" value="sendPolice"><input type="hidden" name="dateId" value="${selectedDate.id}"><button class="btn-filter" type="submit">Gửi CSGT ngay</button></form></c:if></div></c:if></div>
<c:choose><c:when test="${selectedDate.cancelled}"><div class="cancel-summary"><strong>Ngày thi dự kiến đã hủy</strong><p><strong>Lý do:</strong> <c:out value="${selectedDate.cancelReason}"/></p><p><strong>Thời điểm hủy:</strong> <fmt:formatDate value="${selectedDate.cancelledAt}" pattern="dd/MM/yyyy HH:mm"/></p><p><strong>Số lựa chọn đã giải phóng:</strong> ${selectedDate.cancelledRegistrationCount}</p></div></c:when><c:otherwise>
<div style="overflow:auto"><table class="tent-table"><thead><tr><th>Mã HS</th><th>CCCD</th><th>Họ tên</th><th>Email</th><th>Hạng</th><th>Trạng thái</th></tr></thead><tbody><c:forEach var="d" items="${candidates}"><tr><td>#${d.registrationId}</td><td>${d.profile.govIdNo}</td><td><strong><c:out value="${d.profile.fullName}"/></strong></td><td><c:out value="${d.user.email}"/></td><td>${d.licenceDisplayClass}</td><td>Chờ lịch chính thức</td></tr></c:forEach><c:if test="${empty candidates}"><tr><td colspan="6" style="text-align:center;padding:2rem;color:#64748b">Chưa có hồ sơ chọn ngày này.</td></tr></c:if></tbody></table></div>
<c:if test="${candidatePages gt 1}"><nav class="pagination-nav" style="margin-top:1rem"><c:forEach var="p" begin="1" end="${candidatePages}"><a class="page-btn ${p eq candidatePage ? 'active' : ''}" href="${ctx}/manager/tentative-exam-dates?dateId=${selectedDate.id}&amp;tab=${activeTab}&amp;page=${currentPage}&amp;candidatePage=${p}">${p}</a></c:forEach></nav></c:if>
<c:choose><c:when test="${selectedDate.cancellable}"><form id="cancel-date-form" class="cancel-form" method="post" action="${ctx}/manager/tentative-exam-dates" onsubmit="return confirm('Xác nhận hủy ngày thi dự kiến này? Các lựa chọn của thí sinh sẽ được giải phóng.');"><input type="hidden" name="action" value="cancel"><input type="hidden" name="dateId" value="${selectedDate.id}"><label>Lý do hủy<textarea class="input-field" name="cancelReason" maxlength="500" required placeholder="Nhập lý do hủy để lưu vào lịch sử..."></textarea></label><button class="btn-reset" type="submit">Xác nhận hủy</button></form></c:when><c:when test="${selectedDate.locked}"><div class="notice" style="margin-top:1rem;margin-bottom:0;background:#fffbeb;color:#92400e">Ngày dự kiến đã tự động khóa trước 07 ngày làm việc. Thí sinh không thể đăng ký hoặc đổi lựa chọn, cán bộ quản lý cũng không thể hủy.</div></c:when><c:otherwise><div class="notice err" style="margin-top:1rem;margin-bottom:0">Ngày dự kiến đã qua nên không thể hủy.</div></c:otherwise></c:choose>
</c:otherwise></c:choose></section></c:if>
</main><jsp:include page="/views/layout/footer.jsp"><jsp:param name="standalone" value="false"/></jsp:include></div></body></html>
