# SMTP Server Configuration for Gmail
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# Sender Credentials
mail.sender.username=your-gmail-username@gmail.com
mail.sender.password=your-gmail-app-password
