# SMTP Server Configuration for Gmail
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true
mail.smtp.ssl.trust=smtp.gmail.com

# Sender Credentials
mail.sender.username=minhphamnhat2852006@gmail.com
mail.sender.password=cdblvnbohzhxustq
